Sprint 6 solution
Akmula/java-kanban pull request #2
Opened 2024-07-03 14:57 UTC by Akmula

Доработка по ТЗ спринта 6

2024-07-03 16:33 UTC, YazykovMikhail requested changes

2024-07-03 16:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/manager/InMemoryHistoryManager.java
> +    private final Map<Integer, Node> historyTasks = new HashMap<>(); // список истории
До этого поле называлось history сейчас historyTasks, но сейчас там даже таски не храняться, храняться Node
Назови просто history

2024-07-03 16:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/manager/InMemoryHistoryManager.java
> +        historyTasks.put(id, linkLast(task));
Я бы рекомендовал лучше разделить эти вызовы, отедльно  linkLast(task)
и потом уже доабвление в историю, все таки это разные процессы.
Можно будет добавлять то что возвращает linkLast(task) или просто tail

2024-07-03 16:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/manager/InMemoryHistoryManager.java
> +            return null;
лучше возвращать пустой спсиок, чем null
  return history;

2024-07-03 16:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/manager/InMemoryHistoryManager.java
> +    static class Node {
Опусти вниз или подними вверх, а то как то посередине методо вобьявлен класс

2024-07-03 16:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/manager/InMemoryHistoryManager.java
> +        if (historyTasks.get(id) != null) {
получается двойной поиск по хранилищу, тут проверку убери просто вызывай 
 remove(id);

2024-07-03 16:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/manager/InMemoryHistoryManager.java
> +        removeNode(node);
А тут тогда добавь проверку 
```
 Node node = historyTasks.remove(id);
if (node == null) {
return;
}
 removeNode(node);
```

2024-07-04 16:07 UTC, YazykovMikhail approved these changes

2024-07-04 16:59 UTC, merged

2024-07-04 16:59 UTC, Akmula commented
Спасибо.