Sprint 7 solution in file manager
Akmula/java-kanban pull request #5
Opened 2024-07-23 12:02 UTC by Akmula

Версия 4.0
1. Создать класс FileBackedTaskManager.
2. Создать метод save без параметров — он будет сохранять текущее состояние менеджера в указанный файл. 
3. Переопределить каждую модифицирующую операцию так, чтобы сначала выполнялась версия, унаследованная от предка, а затем — метод save. 
4. Создать собственное непроверяемое исключение ManagerSaveException. 
5. Создать статический метод static FileBackedTaskManager loadFromFile(File file), который будет восстанавливать данные менеджера из файла при запуске программы.
6. Добавить тесты для новых функций.

2024-07-24 09:58 UTC, TomattmanYandex requested changes
Комменты в коде

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/exceptions/ManagerFileException.java
> +    private static final String LOAD_MESSAGE = "Ошибка чтения файла!";
интересный вариант
но я бы порекомендовал немного по другому сделать
сделать два класса с ошибками, потому что сообщение стоит оставить для деталей, например, почему не сохранили или не загрузили

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/formatters/CSVFormatter.java
> +        if (type.equals("Epic")) {
я бы порекомендовал одно из двух
1) сделать енам с типами, и использовать его (это вариант получше)
2) вынести в константы эти три строки

используя из енама или константы ты не получишь ошибку если в одном месте, например при записи ты укажешь тип Epic а при считывании EPIC

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/formatters/CSVFormatter.java
> +                task.getEpicId();
откуда у таска появился epicId? по условию и логике его там быть не должно

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/tasks/Task.java
> +    private int epicId;
по условию у таска не бывает не эпика, не сабтаска, не списка сабтасков, и зачем две переменные, сабтаскid и subTaskIds

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/tasks/Task.java
> +    private int epicId;
кстати рекомендация,где идентификаторы использовать не примитивы а классы обертки, 
у примитивов есть значение по умолчанию - 0
и ты не сможешь понять, это реальное значение, или еще не проставленное, ведь это валидный идентифкатор, а если использовать класс обертку, то по умолчанию будет null и ты всегда понимаешь, что это значит что значение не проставлено

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +    private static File file;
зачем нужен сразу file и path одного чего то будет достаточно

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +    private static File file;
а еще не стоит делать эту переменную статичной, потому что так если ты создашь несколько инстансов, они все будут смотреть на один и тот же файл, и это не очень удобно, 
или создашь новый класс с другим файлом, и из старого таск менеджера все теперь запишется в новый файл

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +    public FileBackedTaskManager loadFromFile() {
по условию должен быть статический метод, который вернет файловый таск менеджер привязанный к файлу из параметра
этот метод стоит сделать статическим
так же рекомендую сделать конструктор приватным, чтобы файловый таск менеджер могли создать только через этот статический метод, так ты избежишь того, что создадут файловый таск менеджер без считывания файла, а следовательно данные не оптеряются

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +                if (task instanceof Epic) {
попоробуй сделать это без instanceof это не самый лучший подход
варианта как сделать два
либо в конвертере делаешь метод, который по строке возвращает тип, и в зависимости от значения сетаешь в разные списки, или второй, тип можно запихнуть в классы моделей как неизменяемое значение, и отталкиваться от него

2024-07-24 09:58 UTC, TomattmanYandex commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +        InMemoryTaskManager.setGeneratorId(maxId);
так как в файл мы не пишем сабтаски эпика, все эпики будут с пустым списком сабтасков

2024-07-24 09:58 UTC, TomattmanYandex commented on test/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManagerTest.java
> +    {
для таких целей есть аннотация @BeforeEach она вешается на метод, и этот метод будет вызываться перед каждыйм тестовым методом

2024-07-24 09:58 UTC, TomattmanYandex commented on test/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManagerTest.java
> +    void testSavingAndUploadingEmptyFile() {
по тестам напишу один большой коммент, он будет касаться всех тестов

2024-07-24 09:58 UTC, TomattmanYandex commented on test/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManagerTest.java
> +    void testSavingAndUploadingEmptyFile() {
хорошее имя тестового метода
обычно состоит из трех частей
название тестируемого метода, что должно произойти, при каких условиях
последняя часть опциональна
например
validateFilm_throwValidationException_descriptionLongerThan200
разделяют их или нижними подчеркиваниями или словами should when
нижние подчеркивания нагляднее
структура метода
хороший тетсовый метод можно разделить на три части, которые часто разделяют коментариями
//given
тут подготовка входных данных
//that
тут вызов тестируемого метода
//then
тут проверки

2024-07-29 06:33 UTC, YazykovMikhail requested changes

2024-07-29 06:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/formatters/CSVFormatter.java
> +        return "id;type;title;description;status;epicId";
По заданию разделяется запятыми
Ты сейчас сделаешь и это будет работать, но потом нужно будет портировать данные и окажется чт оформаты разные, хотя в задании было приведен конкретный пример черех запятые

2024-07-29 06:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +    static File file;
Модификтор дсотупа 
private

2024-07-29 06:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/managers/InMemoryTaskManager.java
> +    protected static void setGeneratorId(int currentId) {
Не нужно делать метод статичнфм что бы иметь к нему доступ, лучше все переемнные  в этом классе сделать 
`protected`
Что бы у наследников был прямой доступ

2024-07-29 06:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +        InMemoryTaskManager.setGeneratorId(maxId);
Сделай поля в классе   InMemoryTaskManager модификатором доступа 
protected 
и будет прямой доступ

2024-07-29 06:33 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +                    fileBackedTaskManager.addEpic((Epic) task);
Сделай метод для добавления:
```
protected void addAnyTask(Task task) {
		final int id = task.getId();
		switch (task.getType()) {
			case TASK:
				tasks.put(id, task);
				break;
			case SUBTASK:
				subtasks.put(id, (Subtask) task);
				break;
			case EPIC:
				epics.put(id, (Epic) task);
				break;
		}
	}
```
Используй его
Бизнес методы использовать не стоит, ведь там генерируется id заного, а нам этого не нужно, нам нужно вернуть состояние со старыми id и т.е поля в классе   InMemoryTaskManager будут protected к ним будет прямой доступ

2024-07-31 06:40 UTC, YazykovMikhail approved these changes

2024-07-31 06:40 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/managers/FileBackedTaskManager.java
> +    private static File file;
Статическим его делать не нужно, как было написано до этого в ревью.

2024-07-31 06:40 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/managers/InMemoryTaskManager.java
> +    protected static final Map<Integer, Task> tasks = new HashMap<>(); // карта с задачами
Статичными эти поля делать не нужно

2024-07-31 06:40 UTC, YazykovMikhail commented on src/ru/yandex/javacource/isaev/schedule/managers/InMemoryTaskManager.java
> +    final HistoryManager historyManager = Managers.getDefaultHistory(); // менеджер истории просмотра задач
забыл  protected

2024-08-09 16:47 UTC, merged